### ISSUE TITLE
Nascom-2 on an ESP32

### ISSUE THREAD

**Issue by PeterJensen** [nealcrook/nascom#11]
Hi Neal,

I couldn't find your e-mail, so I'm filing an 'issue', which isn't really an issue :)

I just came across your repo the other day.  What you're doing (Nascom-4) is super cool.

Back in 1980, I built my own Nascom-2 and basically owe my career to this wonderful machine.  Recently, I pulled it down from my Dad's loft, and powered it back up.  It still ran!  40+ years later.  The casette deck didn't.  Rubber bands and acrylic gears doesn't last forever, I guess.

Anyways, a couple of months ago I decided to build a replica based on the ESP32 MCU.  The project turned out better than I had expected.  I'll be demo'ing it at the Vintage Computer Festival here in Silicon Valley tomorrow.

In case you're interested, I uploaded my code and a first cut at documentation today:

  https://github.com/PeterJensen/nascom-esp

In case you're interested.

I forgot to mention, that I've also been trying to restore my stack of old casette tapes.  Decoding 1200/2400 Hz audio reliably was a bit of a challenge.  I wrote a bunch of python code to do it, and it seems to sort-of work:

  https://github.com/PeterJensen/nascom-tape

All the best
Peter Jensen

**Comment by nealcrook** [comment]
Hi Peter,
nice job! I tried a similar thing about 18 months ago (using the same mixture of BitLuni and FabGL libraries!) but got stuck on the keyboard support and then distracted by my "Nascom 4" project. I will need to go back to my old code to remember what the problems were, and then learn how you solved them. Also, I want to compare our approaches to the video setup with BitLuni's library.

I hope you will add a photo of the inside of your case. For my experiment, I used a TTgo board with VGA and PS/2 connector, but it had no SDcard which was a drag.

You and I seem to have travelled over lots of  the same paths (both in the 1980s and recently).. see my "nascon" anything-to-anything format converter and wav2bin tape decoder (both in PERL rather than Python). Your tape decoder looks more sophisticated; the noise filter seems like a useful addition.

I've been experimenting with a raspberry Pi Pico for another project, and thinking about using one for a Nascom emulator (actually, I want to emulate the whole of Nascom 4 including the MAP80 video/disk board).

If you want to extend your design you'll find adding emulated floppy disk support quite straightforward and you can then run PolyDos (another Anders Hejlsberg creation). I even got it running in the browser with extensions to Tommy Thorne's javascript Nascom emulator (https://github.com/nealcrook/jsnascom).

If you want to talk Nascom things with more folk, come to Nascom-Computers on groups.io

I guess you are an ex-pat as I assume the NASCOM didn't sell in the US. I wonder if you have met Tommy as I suspect he's also in California? I hope your demo goes well at the VCF.

Neal.

**Comment by PeterJensen** [comment]
Hi Neal

Funny you should mention Tommy. I've been communicating with him over the last year and met him in person yesterday, for the first time. He brought his real Nascom2. VCF was fantastic. They had a ton of early British micros. I can send a few pictures if you send me an email. <email address deleted>

**Comment by nealcrook** [comment]
Discussion taken to email. Closing issue.
